#!/bin/bash
# #777, section 5 of this directory's README: the end-to-end `detectPocketsAAG()` A/B.
#
# Parts 1 to 5 of the harness run inside one process and are reproducible with
# `swift run Harnesses 777-pocket-isopen` alone. Section 5 is not: it compares the WHOLE call
# between two builds, so it needs `Sources/OCCTSwift/FeatureRecognition.swift` swapped between
# `origin/main`'s version and this branch's and the harness re-run against each. This script is
# that loop, committed so the table in the README can be reproduced rather than taken on trust.
#
# It alternates sides within each round so a load spike is less likely to land on one side only,
# and the README reports the MINIMUM over rounds rather than the median, because a cross-build
# comparison cannot be interleaved the way Part 2's four predicates are. `end-to-end-ab.txt` next
# to this script is the transcript the README's table was read off.
#
# Run from the repo root, with a local Libraries/ present:
#   OCCTSWIFT_LOCAL=1 bash Scripts/repro/777-pocket-isopen/end-to-end-ab.sh
#
# Takes roughly half an hour: six full harness runs plus six rebuilds.
set -u

ROOT=$(git rev-parse --show-toplevel)
cd "$ROOT" || exit 1

SRC=Sources/OCCTSwift/FeatureRecognition.swift
WORK=$(mktemp -d)
OUT="$ROOT/Scripts/repro/777-pocket-isopen/end-to-end-ab.txt"

trap 'cp "$WORK/after.swift" "$SRC" 2>/dev/null; rm -rf "$WORK"' EXIT

cp "$SRC" "$WORK/after.swift"
git show origin/main:"$SRC" > "$WORK/before.swift" || exit 1

: > "$OUT"
{
  echo "# #777 end-to-end A/B: detectPocketsAAG(), origin/main's enclosure test against this branch's."
  echo "# Generated by end-to-end-ab.sh. Read the MINIMUM per side across rounds; see the README."
  echo "# base: $(git rev-parse --short origin/main), branch: $(git rev-parse --short HEAD)"
  echo ""
} >> "$OUT"

for round in 1 2 3; do
  for side in before after; do
    cp "$WORK/$side.swift" "$SRC"
    swift build --target Harnesses > /dev/null 2>&1 || exit 1
    echo "=== round $round, $side ===" >> "$OUT"
    swift run Harnesses 777-pocket-isopen 2>/dev/null \
      | sed -n '/Part 3:/,/Part 4:/p' >> "$OUT"
  done
done

cp "$WORK/after.swift" "$SRC"
swift build --target Harnesses > /dev/null 2>&1
echo "done" >> "$OUT"
