#!/usr/bin/env python3
"""Gate: every Scripts/patches-wasi/ patch was authored against the carried-patch tree (#2168).

`Scripts/build-occt-wasm.sh` applies `Scripts/patches/` first and `Scripts/patches-wasi/` second,
so the ORDER was always right. What PR #2076 got wrong is the state its fifteen WASI patches were
authored and checked in: a pristine `V8_0_1`. That is not the tree this repo builds. Nine carried
patches inject `std::mutex` and `std::recursive_mutex` into OCCT (#341, #344, #349, #353, #374,
#1153, #1154, #1157, #1403), which is how nobody noticed that 15 of the 76 threading-dependent
files are files we patch ourselves.

THE RULE, stated once in `okf/policies/wasi-patch-base.md` and enforced here: a WASI patch is
generated by `git diff` in `Libraries/occt-src` AFTER the carried set is applied, and verified by
`git apply --check` in that same state. A patch that applies to vanilla but not to the patched
tree, or the reverse, is a defect.

WHY THE GATE READS PATCH TEXT AND NOT A SOURCE TREE. `ci.yml`'s `gate-scripts` job is pure Python
over the repo's own text: no OCCT, no `Libraries/occt-src`, no build, no network, and it must not
grow one. That is the same argument `check-patch-deletes-guarded-symbol.py` (#2058) and
`check-preprocessor-balance.py` (#2167) make for living in that job rather than an hour into
`kernel-integration.yml`. `git apply --check` is not reconstructible from text. What IS
reconstructible is every way the two patch sets can contradict each other, and that is the part
most likely to rot at the next kernel repin.

This is NOT `check-preprocessor-balance.py` a second time. That gate asks whether a patch leaves
the file's `#if`/`#else`/`#endif` balanced. This one asks what tree the patch was cut from.

THE FIVE RULES, each with what it catches and what it deliberately does not.

  1. CARRIED_COLLISION. A file targeted by both a `Scripts/patches/` patch and a
     `Scripts/patches-wasi/` patch, where the WASI patch does not declare which carried patch it
     sits on top of. Both filenames are named, because "some carried patch touches this too" is
     not a thing anybody can act on. The declaration is a preamble trailer:

         Applies-After: 0033-Interface_Static-thread-safety-mutex-1157.patch

     one line per carried patch sharing the file. It is not paperwork: it is the record that
     somebody regenerated the diff in the patched state, and it is what rots loudly at the next
     repin rather than quietly (rule 2). There is no collision in the tree today, which is exactly
     why the rule is worth having before #2173 writes the patches that will create one.

  2. STALE_TRAILER. An `Applies-After:` naming a carried patch that is not in `Scripts/patches/`,
     or that is there but does not touch the file it is claimed for. Carried patches are retired
     (0032 was, unshipped) and renumbered sets get repinned; a trailer that no longer resolves
     means the state the WASI patch was verified in no longer exists.

  3. STALE_CONTEXT. A WASI patch whose context or removed lines carry a line that a carried patch
     REMOVES from that same file and does not add back. That line is not in the patched tree, so
     the WASI patch cannot have been diffed against it. This is proof, not suspicion. Trivial
     lines (a lone brace, a blank, anything under twelve characters of substance) are excluded:
     they match everywhere and would report coincidence as evidence.

  4. FOREIGN_MEMBER. An added line using an OCCT member name (`my<Name>`, OCCT's convention) that
     no context or removed line in EITHER patch set mentions for that class, and that no added
     line declares. This is the fingerprint of a hunk written against a different file's state.

     It is what rejects PR #2076's `wasi-osd-directory.patch`, and that patch is worth describing
     exactly, because it is not what the issue's one-line summary suggests. Its base was correct:
     `index 5dd52195..c2426330` names the real `V8_0_1` blob, it applies cleanly to both the
     pristine and the carried-patched tree, and applying it reproduces the post-image blob the
     `index` line claims. Measured, all three. What is wrong with it is that its added code is
     `OSD_File`'s, pasted into `OSD_Directory`:

         +  myFileChannel = open(aTmpName2, O_CREAT | O_EXCL | O_RDWR, 0600);

     `OSD_Directory` has no `myFileChannel`. It regressed `OSD_Directory::BuildTemporary` from the
     `mkdir` form to an `open()` form that cannot compile, and no base-state check of any kind can
     see it, because the base was not the thing that was wrong. The file was. Measured over the
     whole #2076 corpus this rule reports exactly one member, `myFileChannel`, and reports nothing
     on the two patches in the tree today.

     Its vocabulary is the patch text, which is thin: a member the patch neither shows in context
     nor declares is reported even where the file really does have it. `--tree` settles that case
     against the real file. The remedy in the gate is to widen the hunk so the member appears in
     context, which is also what makes the patch readable.

  5. COINCIDENT_TARGET. Two `Scripts/patches-wasi/` patches editing the same file. The second
     states its line numbers against the tree as the first left it, and nothing in the directory
     records which of them is first: `build-occt-wasm.sh` walks the glob in filename order, which
     is not a decision anybody made. One file, one patch.

WHAT THE TEXT-ONLY MODE CANNOT CATCH, stated plainly. It cannot run `git apply --check`. A WASI
patch whose context simply does not exist in the patched tree, for a file no carried patch touches,
is invisible to every rule above, and so is one whose hunk offsets have drifted. Those need the
tree. `--tree DIR` (default `Libraries/occt-src`) is that mode: it requires the carried set to be
applied, verifies each WASI patch's `index` pre-image blob against `git hash-object` of the target
in that state, and runs the real `git apply --check`. It is NOT part of `gate-scripts`, which has
no checkout, and per #2098 a mode that examined nothing must fail rather than pass: `--require-tree`
turns a missing tree from a printed note into an error.

Usage:
  Scripts/check-wasi-patch-base.py                    # the gate: patch text only
  Scripts/check-wasi-patch-base.py --list             # targets, trailers and member vocabulary
  Scripts/check-wasi-patch-base.py --tree             # + the real check against Libraries/occt-src
  Scripts/check-wasi-patch-base.py --tree DIR --require-tree
  Scripts/check-wasi-patch-base.py --self-test
"""
import argparse
import glob
import os
import re
import subprocess
import sys

CARRIED_GLOB = 'Scripts/patches/*.patch'
WASI_GLOB = 'Scripts/patches-wasi/*.patch'
DEFAULT_TREE = 'Libraries/occt-src'

HUNK_RE = re.compile(r'^@@ -(\d+)(?:,(\d+))? \+(\d+)(?:,(\d+))? @@')
INDEX_RE = re.compile(r'^index ([0-9a-f]{7,40})\.\.([0-9a-f]{7,40})')
TRAILER_RE = re.compile(r'^[ \t]*Applies-After:[ \t]*(\S+)[ \t]*$')

# OCCT's member convention: `my` followed by an upper-case letter. Deliberately not `m_` or a bare
# lower-case name, because those two forms are also how OCCT spells locals and parameters, and a
# rule that reported a local would fire on every correct patch that adds one.
MEMBER_RE = re.compile(r'\bmy[A-Z]\w*')

# A declaration introduces the member rather than using one that must already exist. Something has
# to precede the name (a type), which is what separates `std::atomic_flag mySpinlock;` from
# `myFileChannel = open(...)`. #2076's incallocator and Standard_Condition patches declare four
# members between them and must not be reported; its OSD_Directory patch declares none.
DECL_RE = re.compile(r'^[ \t]*[A-Za-z_][\w:<>,\s\*&]*[\s\*&](my[A-Z]\w*)\s*(?:;|=|\{|\[|\))')

# A removed line is only evidence of a stale base when it is distinctive. A brace, a blank or a
# lone `#endif` appears in every file in OCCT, so matching one proves nothing.
SUBSTANCE_MIN = 12


def class_stem(target):
    """The class a source path belongs to: `.../OSD_Directory.cxx` gives `OSD_Directory`.

    Pooling `.cxx` with `.hxx` is what lets a member declared in the header patch count as known
    to the implementation patch, which is #2076's `mySpinlock`, declared in
    `wasi-incallocator.hxx.patch` and used in `wasi-incallocator.cxx.patch`.
    """
    return os.path.splitext(os.path.basename(target))[0] if target else ''


class Hunk:
    """One hunk: its target file, its old-file span, and its (sign, text, patch line) entries."""

    def __init__(self, target, old_start, old_len, header_line):
        self.target = target
        self.old_start = old_start
        self.old_len = old_len
        self.header_line = header_line
        self.entries = []

    def old_span(self):
        return (self.old_start, self.old_start + max(self.old_len, 1) - 1)


def parse_patch(text):
    """Every hunk in a patch, in order.

    Hunk bodies are consumed by the counts in the `@@` header rather than by "a line starting with
    `-` is a removal". That is what keeps the `---`/`+++` file headers and the patch's own prose
    preamble out, and several carried patches open with a `- ...` bullet list. `Scripts/patches/
    0028-...` is the one that made `check-patch-deletes-guarded-symbol.py` read prose as deleted
    source.
    """
    hunks = []
    target = None
    hunk = None
    remaining_old = remaining_new = 0
    for number, line in enumerate(text.splitlines(), start=1):
        if remaining_old <= 0 and remaining_new <= 0:
            hunk = None
            if line.startswith('+++ '):
                target = line[4:].split('\t')[0].strip()
                if target.startswith('b/'):
                    target = target[2:]
            elif line.startswith('@@ '):
                match = HUNK_RE.match(line)
                if match:
                    remaining_old = int(match.group(2) or 1)
                    remaining_new = int(match.group(4) or 1)
                    hunk = Hunk(target, int(match.group(1)), remaining_old, number)
                    hunks.append(hunk)
            continue
        if line.startswith('\\'):          # "\ No newline at end of file" spends neither count
            continue
        if line.startswith('-'):
            hunk.entries.append(('-', line[1:], number))
            remaining_old -= 1
        elif line.startswith('+'):
            hunk.entries.append(('+', line[1:], number))
            remaining_new -= 1
        else:
            hunk.entries.append((' ', line[1:] if line[:1] == ' ' else line, number))
            remaining_old -= 1
            remaining_new -= 1
    return hunks


def parse_trailers(text):
    """`Applies-After:` declarations, from anywhere outside a hunk body.

    Read off the raw text rather than the preamble alone, so a trailer written under a
    `diff --git` header (which is where `git format-patch` output puts a note) is still seen. A
    line inside a hunk body always carries a leading space, `+` or `-`, so the anchored regex
    cannot pick one up.
    """
    return [match.group(1) for match in
            (TRAILER_RE.match(line) for line in text.splitlines()) if match]


def parse_index(text):
    """Per target file, the (pre, post) blob names a `git diff` stamped into its `index` line.

    Absent from a hand-trimmed patch, and both patches in `Scripts/patches-wasi/` today are hand
    trimmed, so its absence is not a defect. When it is there it is the exact identity of the tree
    the patch was cut from, which is what `--tree` checks.
    """
    out = {}
    target = None
    pending = None
    for line in text.splitlines():
        match = INDEX_RE.match(line)
        if match:
            pending = (match.group(1), match.group(2))
            continue
        if line.startswith('+++ '):
            target = line[4:].split('\t')[0].strip()
            if target.startswith('b/'):
                target = target[2:]
            if pending and target:
                out[target] = pending
            pending = None
    return out


def targets_of(hunks):
    return sorted({hunk.target for hunk in hunks if hunk.target})


def substantive(line):
    body = line.strip()
    return len(body) >= SUBSTANCE_MIN and re.search(r'[A-Za-z_]{3}', body) is not None


# --- the five rules --------------------------------------------------------------------------


def collisions(carried, wasi):
    """Rules 1 and 2: a shared target file, and whether the WASI patch declares what it sits on.

    Returns (findings, collision_pairs), the second for --list and for the clean-run summary.
    """
    found = []
    pairs = []
    carried_by_target = {}
    for name, hunks in carried.items():
        for target in targets_of(hunks):
            carried_by_target.setdefault(target, []).append(name)

    for name in sorted(wasi):
        declared = set(parse_trailers(wasi[name]['text']))
        resolved = set()
        for target in targets_of(wasi[name]['hunks']):
            for other in carried_by_target.get(target, []):
                pairs.append((name, other, target))
                if os.path.basename(other) in declared:
                    resolved.add(os.path.basename(other))
                else:
                    found.append((
                        'CARRIED_COLLISION', name, target,
                        'the carried patch %s edits this file too, and this patch does not declare '
                        'it. Regenerate the diff with the carried set applied, then add '
                        '`Applies-After: %s` to the preamble.'
                        % (other, os.path.basename(other))))
        for claim in sorted(declared - resolved):
            path = os.path.join('Scripts', 'patches', claim)
            if claim not in {os.path.basename(c) for c in carried}:
                found.append((
                    'STALE_TRAILER', name, None,
                    '`Applies-After: %s` names no patch in Scripts/patches/. It was retired or '
                    'renumbered, so the state this patch was verified in no longer exists; '
                    'regenerate and re-verify.' % claim))
            else:
                found.append((
                    'STALE_TRAILER', name, None,
                    '`Applies-After: %s` names a carried patch that touches none of this patch\'s '
                    'target files. Either the trailer is wrong or the patch was retargeted.'
                    % os.path.relpath(path)))
    return found, pairs


def stale_context(carried, wasi):
    """Rule 3: a WASI context or removed line that the carried set deletes from that same file."""
    found = []
    removed_by_target = {}
    for name, hunks in carried.items():
        for hunk in hunks:
            added = {text.strip() for sign, text, _ in hunk.entries if sign == '+'}
            for sign, text, _ in hunk.entries:
                if sign == '-' and substantive(text) and text.strip() not in added:
                    removed_by_target.setdefault(hunk.target, {}).setdefault(
                        text.strip(), set()).add(name)

    for name in sorted(wasi):
        for hunk in wasi[name]['hunks']:
            gone = removed_by_target.get(hunk.target, {})
            for sign, text, number in hunk.entries:
                if sign == '+':
                    continue
                owners = gone.get(text.strip())
                if owners:
                    found.append((
                        'STALE_CONTEXT', name, hunk.target,
                        'patch line %d carries `%s`, which %s removes from this file. That line is '
                        'not in the tree build-occt-wasm.sh applies this to, so this diff was cut '
                        'from the unpatched source.'
                        % (number, text.strip(), ' and '.join(sorted(owners)))))
    return found


def foreign_members(carried, wasi):
    """Rule 4: an added line using a member no patch in either set shows or declares."""
    known = {}
    declared = {}
    for store in (carried, wasi):
        for name in store:
            hunks = store[name] if isinstance(store[name], list) else store[name]['hunks']
            for hunk in hunks:
                stem = class_stem(hunk.target)
                for sign, text, _ in hunk.entries:
                    if sign == '+':
                        match = DECL_RE.match(text)
                        if match:
                            declared.setdefault(stem, set()).add(match.group(1))
                    else:
                        known.setdefault(stem, set()).update(MEMBER_RE.findall(text))

    found = []
    seen = set()
    for name in sorted(wasi):
        for hunk in wasi[name]['hunks']:
            stem = class_stem(hunk.target)
            for sign, text, number in hunk.entries:
                if sign != '+':
                    continue
                for member in MEMBER_RE.findall(text):
                    if member in known.get(stem, ()) or member in declared.get(stem, ()):
                        continue
                    if (name, stem, member) in seen:
                        continue
                    seen.add((name, stem, member))
                    found.append((
                        'FOREIGN_MEMBER', name, hunk.target,
                        'patch line %d uses `%s`, which no context line shows in %s and no added '
                        'line declares. A member that belongs to another class is what a hunk '
                        'written against the wrong file looks like (#2076 pasted OSD_File\'s '
                        '`myFileChannel` into OSD_Directory). Widen the hunk so the member appears '
                        'in context, or fix the patch.' % (number, member, stem)))
    return found


def coincident_targets(wasi):
    """Rule 5: two WASI patches editing one file, whose relative order nobody has decided."""
    found = []
    by_target = {}
    for name in sorted(wasi):
        for target in targets_of(wasi[name]['hunks']):
            by_target.setdefault(target, []).append(name)
    for target, names in sorted(by_target.items()):
        if len(names) > 1:
            found.append((
                'COINCIDENT_TARGET', ', '.join(names), target,
                '%d patches in Scripts/patches-wasi/ edit this file. Only the first was cut from '
                'the carried-patch tree; the rest state their line numbers against whatever the '
                'ones before them left, and build-occt-wasm.sh orders them by filename, which is '
                'not a decision anybody made. One file, one patch.' % len(names)))
    return found


# --- the deeper mode: the real check against a checkout -----------------------------------------


def git(tree, *args):
    """(returncode, stdout) for a git command in `tree`. Never mutates the tree."""
    result = subprocess.run(('git', '-C', tree) + args,
                            capture_output=True, text=True, check=False)
    return result.returncode, result.stdout.strip()


def carried_state(tree, carried):
    """Which carried patches are already applied in `tree`, by reverse-apply.

    `git apply --check --reverse` succeeds exactly when the patch's post-image is present, which
    is the question, and it writes nothing.
    """
    applied, missing = [], []
    for name in sorted(carried):
        code, _ = git(tree, 'apply', '--check', '--reverse', os.path.abspath(name))
        (applied if code == 0 else missing).append(name)
    return applied, missing


def scan_tree(tree, carried, wasi):
    """The real check: the state, then each WASI patch's blob identity and `git apply --check`."""
    problems = []
    applied, missing = carried_state(tree, carried)
    if missing:
        problems.append((
            'TREE_NOT_PATCHED', tree, None,
            '%d of %d carried patches are not applied here (%s%s). A WASI patch is authored and '
            'verified with the carried set applied, so this tree cannot answer the question. Run '
            'Scripts/build-occt.sh, or apply Scripts/patches/ by hand first.'
            % (len(missing), len(carried), ', '.join(os.path.basename(m) for m in missing[:3]),
               ', ...' if len(missing) > 3 else '')))
        return problems, 0

    examined = 0
    for name in sorted(wasi):
        stamped = parse_index(wasi[name]['text'])
        for target, (pre, _post) in sorted(stamped.items()):
            code, actual = git(tree, 'hash-object', target)
            if code != 0:
                problems.append(('MISSING_TARGET', name, target,
                                 'the patch names a file this checkout does not have.'))
                continue
            if not actual.startswith(pre) and not pre.startswith(actual[:len(pre)]):
                problems.append((
                    'WRONG_BASE', name, target,
                    'the patch\'s `index` line names pre-image blob %s, and this file is %s with '
                    'the carried set applied. The diff was cut from a different tree.'
                    % (pre, actual[:len(pre)])))
        code, _ = git(tree, 'apply', '--check', os.path.abspath(name))
        if code != 0:
            reverse, _ = git(tree, 'apply', '--check', '--reverse', os.path.abspath(name))
            if reverse == 0:
                print('  note: %s is already applied in %s, so --check cannot re-verify it. '
                      'build-occt-wasm.sh treats that as success.' % (name, tree))
            else:
                problems.append((
                    'DOES_NOT_APPLY', name, None,
                    '`git apply --check` fails in %s with the carried set applied, and the patch '
                    'is not already applied either. This is the defect the rule exists to stop: '
                    'a patch verified against some other state.' % tree))
        examined += 1
    return problems, examined


# --- running -------------------------------------------------------------------------------


def collect():
    """(carried, wasi). Carried maps path to hunks; WASI maps path to {'text', 'hunks'}."""
    carried = {}
    for path in sorted(glob.glob(CARRIED_GLOB)):
        with open(path, encoding='utf-8', errors='replace') as handle:
            carried[path] = parse_patch(handle.read())
    wasi = {}
    for path in sorted(glob.glob(WASI_GLOB)):
        with open(path, encoding='utf-8', errors='replace') as handle:
            text = handle.read()
        wasi[path] = {'text': text, 'hunks': parse_patch(text)}
    return carried, wasi


def findings(carried, wasi):
    collision_found, pairs = collisions(carried, wasi)
    return (collision_found
            + stale_context(carried, wasi)
            + foreign_members(carried, wasi)
            + coincident_targets(wasi)), pairs


def report(found):
    for kind, name, target, detail in found:
        print('  %s  %s' % (kind, name))
        print('    %s' % (target or '(the patch as a whole)'))
        print('    %s' % detail)
        print('')


def run(tree=None, require_tree=False):
    carried, wasi = collect()
    if not wasi:
        print('check-wasi-patch-base: no patches found under %s. This gate reads patch text, so '
              'an empty population is a broken run, not a clean tree.' % WASI_GLOB)
        return 1
    if not carried:
        print('check-wasi-patch-base: no patches found under %s. The whole question is how the '
              'WASI set relates to the carried set, so an empty carried set is a broken run.'
              % CARRIED_GLOB)
        return 1

    # static-gates.md: assert the view is plausible, not only the verdict. A patch file that parsed
    # to no hunk was never examined, and a detector reporting clean on a population it never read
    # is the failure this family exists to prevent.
    blind = [name for name in sorted(wasi) if not wasi[name]['hunks']]
    blind += [name for name in sorted(carried) if not carried[name]]
    if blind:
        print('check-wasi-patch-base: %d patch file(s) parsed to no hunk at all, so they were '
              'never examined:' % len(blind))
        for name in blind:
            print('  %s' % name)
        return 1

    found, pairs = findings(carried, wasi)

    tree_problems, examined = [], 0
    if tree is not None:
        if os.path.isdir(os.path.join(tree, '.git')) or os.path.isfile(os.path.join(tree, '.git')):
            tree_problems, examined = scan_tree(tree, carried, wasi)
        elif require_tree:
            print('check-wasi-patch-base: --require-tree was given and %s is not a git checkout, '
                  'so the real check examined nothing. A run that examined nothing fails rather '
                  'than passes (#2098).' % tree)
            return 1
        else:
            print('check-wasi-patch-base: note, %s is not a git checkout, so the real '
                  '`git apply --check` was skipped and only the patch-text rules ran. Pass '
                  '--require-tree where the checkout is meant to be there.\n' % tree)
        if require_tree and not examined and not tree_problems:
            print('check-wasi-patch-base: --require-tree was given and no WASI patch was examined '
                  'against %s.' % tree)
            return 1

    if found or tree_problems:
        if found:
            print('check-wasi-patch-base: %d patch-base defect(s) in the patch text\n' % len(found))
            report(found)
        if tree_problems:
            print('check-wasi-patch-base: %d defect(s) against the checkout at %s\n'
                  % (len(tree_problems), tree))
            report(tree_problems)
        print('A Scripts/patches-wasi/ patch is generated by `git diff` in Libraries/occt-src '
              'AFTER the carried\nset is applied, and verified by `git apply --check` in that same '
              'state. PR #2076 authored fifteen\nagainst a pristine V8_0_1; #2168 is the record, '
              'and okf/policies/wasi-patch-base.md is the rule.')
        return 1

    summary = ('check-wasi-patch-base: clean, %d WASI patches against %d carried patches, '
               '%d shared target file(s)' % (len(wasi), len(carried), len(pairs)))
    if tree is not None and examined:
        summary += (' (%d also verified by `git apply --check` under %s)' % (examined, tree))
    print(summary)
    return 0


def list_inventory():
    carried, wasi = collect()
    carried_by_target = {}
    for name, hunks in carried.items():
        for target in targets_of(hunks):
            carried_by_target.setdefault(target, []).append(os.path.basename(name))
    print('%d WASI patches, %d carried patches' % (len(wasi), len(carried)))
    for name in sorted(wasi):
        print('  %s' % name)
        trailers = parse_trailers(wasi[name]['text'])
        stamped = parse_index(wasi[name]['text'])
        for target in targets_of(wasi[name]['hunks']):
            shared = carried_by_target.get(target, [])
            print('    %-72s %s' % (target,
                                    'also carried: ' + ', '.join(shared) if shared else 'wasi only'))
            if target in stamped:
                print('      index %s..%s' % stamped[target])
        for trailer in trailers:
            print('      Applies-After: %s' % trailer)
    return 0


# --- self-test ---------------------------------------------------------------------------------
#
# The #2076 patches are NOT vendored here. They are on the `wasm-bridge-spike` branch, which is
# where a real-world corpus belongs; committing them into Scripts/patches-wasi/ would put fifteen
# files that break the kernel into the directory build-occt-wasm.sh applies. These fixtures are
# minimal synthetic versions of the same shapes, and every one was checked by removing the rule it
# exercises and watching the case fail.

CARRIED_MUTEX = '''\
--- a/src/DataExchange/TKXSBase/Interface/Interface_Static.cxx
+++ b/src/DataExchange/TKXSBase/Interface/Interface_Static.cxx
@@ -30,6 +30,9 @@ static Interface_StaticTable& staticTable()
   static Interface_StaticTable aTable;
-  return aTable;
+  static std::recursive_mutex aMutex;
+  std::lock_guard<std::recursive_mutex> aLock(aMutex);
+  return ensureStaticTable(aTable);
 }
'''

# The WASI patch below quotes `return aTable;` as context, and the carried patch above removes
# exactly that line, so this diff cannot have been cut from the patched tree.
WASI_STALE = '''\
--- a/src/DataExchange/TKXSBase/Interface/Interface_Static.cxx
+++ b/src/DataExchange/TKXSBase/Interface/Interface_Static.cxx
@@ -30,4 +30,6 @@ static Interface_StaticTable& staticTable()
   static Interface_StaticTable aTable;
   return aTable;
+#ifdef __wasi__
+  (void)0;
+#endif
 }
'''

WASI_COLLIDING = '''\
--- a/src/DataExchange/TKXSBase/Interface/Interface_Static.cxx
+++ b/src/DataExchange/TKXSBase/Interface/Interface_Static.cxx
@@ -60,4 +60,6 @@ void Interface_Static::Init()
   anItem->SetValue(theValue);
+#ifdef __wasi__
+  (void)anItem;
+#endif
   return;
 }
'''

WASI_COLLIDING_DECLARED = ('Applies-After: 0033-Interface_Static-thread-safety-mutex-1157.patch\n\n'
                           + WASI_COLLIDING)

WASI_TRAILER_UNKNOWN = ('Applies-After: 0099-no-such-patch.patch\n\n'
                        + WASI_COLLIDING_DECLARED)

# #2076's wasi-osd-directory.patch, reduced to the line that gives it away: `myFileChannel` is an
# OSD_File member, and this patch edits OSD_Directory.
WASI_FOREIGN_MEMBER = '''\
--- a/src/FoundationClasses/TKernel/OSD/OSD_Directory.cxx
+++ b/src/FoundationClasses/TKernel/OSD/OSD_Directory.cxx
@@ -152,4 +152,8 @@ OSD_Directory OSD_Directory::BuildTemporary()
   char aTmpName[] = "/tmp/CSFXXXXXX";
+#ifdef __wasi__
+  myFileChannel = open(aTmpName, O_CREAT | O_EXCL | O_RDWR, 0600);
+#else
   if (nullptr == mkdtemp(aTmpName))
+#endif
   {
'''

# The same shape, correct: the member the added line writes is one the hunk shows in context.
WASI_KNOWN_MEMBER = '''\
--- a/src/FoundationClasses/TKernel/OSD/OSD_Directory.cxx
+++ b/src/FoundationClasses/TKernel/OSD/OSD_Directory.cxx
@@ -107,4 +107,8 @@ void OSD_Directory::Build(const OSD_Protection& theProtect)
   myPath.SystemName(aBuffer);
+#ifdef __wasi__
+  myPath.SetName(aBuffer);
+#else
   umask(0);
+#endif
   int aStatus = mkdir(aBuffer.ToCString(), anInternalProt);
'''

# A member the patch DECLARES, which is #2076's mySpinlock: introduced in the header hunk and used
# in the implementation hunk, and reporting it would fail every correct patch that adds a member.
WASI_DECLARES_MEMBER = '''\
--- a/src/FoundationClasses/TKernel/NCollection/NCollection_IncAllocator.hxx
+++ b/src/FoundationClasses/TKernel/NCollection/NCollection_IncAllocator.hxx
@@ -144,2 +144,5 @@ public:
   unsigned int myBlockCount = 0;
+#ifdef __wasi__
+  std::unique_ptr<std::atomic_flag> mySpinlock;
+#endif
   IBlock* myAllocationHeap = nullptr;
'''

WASI_USES_DECLARED_MEMBER = '''\
--- a/src/FoundationClasses/TKernel/NCollection/NCollection_IncAllocator.cxx
+++ b/src/FoundationClasses/TKernel/NCollection/NCollection_IncAllocator.cxx
@@ -78,2 +78,5 @@ void NCollection_IncAllocator::SetThreadSafe(const bool theIsThreadSafe)
   myIsThreadSafe = theIsThreadSafe;
+#ifdef __wasi__
+  mySpinlock.reset(new std::atomic_flag);
+#endif
 }
'''

# A brace and a blank line are removed by the carried patch and quoted by the WASI one. Reporting
# that as a stale base would fire on almost every patch pair in the repo.
CARRIED_TRIVIAL = '''\
--- a/src/FoundationClasses/TKernel/OSD/OSD_Host.cxx
+++ b/src/FoundationClasses/TKernel/OSD/OSD_Host.cxx
@@ -20,4 +20,4 @@ void OSD_Host::Values()
   int anIndex = 0;
-  {
+  { // reformatted
   anIndex = 1;
'''

WASI_TRIVIAL_CONTEXT = '''\
--- a/src/FoundationClasses/TKernel/OSD/OSD_Host.cxx
+++ b/src/FoundationClasses/TKernel/OSD/OSD_Host.cxx
@@ -40,3 +40,5 @@ void OSD_Host::Values()
   {
+#ifdef __wasi__
+  (void)0;
+#endif
   anIndex = 2;
'''

WASI_SECOND_ON_SAME_FILE = '''\
--- a/src/FoundationClasses/TKernel/OSD/OSD_Directory.cxx
+++ b/src/FoundationClasses/TKernel/OSD/OSD_Directory.cxx
@@ -200,2 +200,5 @@ void OSD_Directory::Reset()
   myPath.Reset();
+#ifdef __wasi__
+  (void)0;
+#endif
 }
'''

PROSE_PREAMBLE = '''\
Notes on this patch:

- myFileChannel is deliberately NOT used here, see #2076.
- the bullet above is prose, and a parser reading it as a removed line would put `myFileChannel`
  into the known-member vocabulary and go blind to rule 4.

diff --git a/src/FoundationClasses/TKernel/OSD/OSD_Directory.cxx b/src/FoundationClasses/TKernel/OSD/OSD_Directory.cxx
--- a/src/FoundationClasses/TKernel/OSD/OSD_Directory.cxx
+++ b/src/FoundationClasses/TKernel/OSD/OSD_Directory.cxx
@@ -152,2 +152,5 @@ OSD_Directory OSD_Directory::BuildTemporary()
   char aTmpName[] = "/tmp/CSFXXXXXX";
+#ifdef __wasi__
+  myFileChannel = open(aTmpName, O_CREAT, 0600);
+#endif
   if (nullptr == mkdtemp(aTmpName))
'''

INDEXED = '''\
diff --git a/src/FoundationClasses/TKernel/OSD/OSD_Path.cxx b/src/FoundationClasses/TKernel/OSD/OSD_Path.cxx
index a39c0c84..792070c6 100644
--- a/src/FoundationClasses/TKernel/OSD/OSD_Path.cxx
+++ b/src/FoundationClasses/TKernel/OSD/OSD_Path.cxx
@@ -40,2 +40,5 @@ static OSD_SysType whereAmI()
   return OSD_Aix;
+#ifdef __wasi__
+  return OSD_Default;
+#endif
 #else
'''


def as_carried(*texts):
    return {'Scripts/patches/%04d-fixture.patch' % (index + 10): parse_patch(text)
            for index, text in enumerate(texts)}


def as_carried_named(name, text):
    return {'Scripts/patches/' + name: parse_patch(text)}


def as_wasi(*texts):
    return {'Scripts/patches-wasi/wasi-fixture-%d.patch' % index:
            {'text': text, 'hunks': parse_patch(text)}
            for index, text in enumerate(texts)}


def self_test():
    carried_static = as_carried_named(
        '0033-Interface_Static-thread-safety-mutex-1157.patch', CARRIED_MUTEX)

    cases = [
        ('#2076: a WASI patch quoting a line the carried set deletes',
         'rule 3. The carried mutex patch removes `return aTable;` and this diff quotes it as '
         'context, which is proof the diff was cut from the unpatched source',
         carried_static, as_wasi(WASI_STALE), ['CARRIED_COLLISION', 'STALE_CONTEXT']),

        ('a WASI patch sharing a file with a carried patch and declaring nothing',
         'rule 1 on its own: the hunks do not overlap and no context is stale, so rule 3 is '
         'silent and only the undeclared collision fires',
         carried_static, as_wasi(WASI_COLLIDING), ['CARRIED_COLLISION']),

        ('the same patch with `Applies-After:` naming the carried patch (correct)',
         'rule 1\'s escape hatch, which is the whole reason the rule is usable: a legitimate '
         'overlap is declared once and stays green until the carried patch moves',
         carried_static, as_wasi(WASI_COLLIDING_DECLARED), []),

        ('`Applies-After:` naming a patch that is not in Scripts/patches/',
         'rule 2, the repin tripwire: a retired or renumbered carried patch leaves the trailer '
         'pointing at a state that no longer exists, and the declaration must stop working',
         carried_static, as_wasi(WASI_TRAILER_UNKNOWN), ['STALE_TRAILER']),

        ('#2076: OSD_File\'s `myFileChannel` pasted into OSD_Directory',
         'rule 4, and it is the only rule that fires on #2076\'s wasi-osd-directory.patch, whose '
         'base was correct: it applies to both trees and its index blobs match',
         as_carried(), as_wasi(WASI_FOREIGN_MEMBER), ['FOREIGN_MEMBER']),

        ('an added line writing a member the hunk shows in context (correct)',
         'rule 4\'s known-member vocabulary. Without it every WASI patch that touches a member at '
         'all would be reported',
         as_carried(), as_wasi(WASI_KNOWN_MEMBER), []),

        ('a member declared in the header patch and used in the implementation patch (correct)',
         'rule 4\'s DECL_RE and the .cxx/.hxx pooling in class_stem, which is #2076\'s mySpinlock '
         'exactly: declared in wasi-incallocator.hxx.patch, used in wasi-incallocator.cxx.patch',
         as_carried(), as_wasi(WASI_DECLARES_MEMBER, WASI_USES_DECLARED_MEMBER), []),

        ('a carried patch removing a lone brace that a WASI patch quotes (correct)',
         'rule 3\'s substantive() filter. A brace, a blank or a short line appears in every OCCT '
         'file, so matching one is coincidence rather than evidence',
         as_carried_named('0016-fixture.patch', CARRIED_TRIVIAL),
         as_wasi(WASI_TRIVIAL_CONTEXT), ['CARRIED_COLLISION']),

        ('two WASI patches editing the same file',
         'rule 5. Each is individually fine; what is wrong is that the second states its line '
         'numbers against whatever the first left, and filename order is not a decision',
         as_carried(), as_wasi(WASI_KNOWN_MEMBER, WASI_SECOND_ON_SAME_FILE),
         ['COINCIDENT_TARGET']),

        ('a prose preamble whose bullet names the very member rule 4 looks for',
         'the count-driven hunk parser. A parser that read `- myFileChannel is deliberately ...` '
         'as a removed line would add the member to the known vocabulary and report the patch '
         'clean, which is the blind-detector failure this family exists to prevent',
         as_carried(), as_wasi(PROSE_PREAMBLE), ['FOREIGN_MEMBER']),
    ]

    failed = 0
    print('patch-text cases')
    for name, isolates, carried, wasi, expected in cases:
        found, _ = findings(carried, wasi)
        got = sorted(kind for kind, _, _, _ in found)
        ok = got == sorted(expected)
        failed += not ok
        print('  %s %s' % ('ok  ' if ok else 'MISS', name))
        print('       isolates: %s' % isolates)
        if not ok:
            print('       expected %s, got %s' % (sorted(expected), got))

    print('parser cases')
    parser_cases = [
        ('a normal patch parses to at least one hunk', len(parse_patch(WASI_STALE)) >= 1),
        # Not decorative: every fixture here was first written with a hand-guessed `@@` count, and
        # an over-large count makes the parser consume the NEXT hunk header as body, so a two-hunk
        # fixture parses to one and the rule it exercises reports nothing while the fixture looks
        # correct. This is the assertion that separates the two.
        ('every fixture parses to as many hunks as it has `@@` headers',
         all(len(parse_patch(text)) == text.count('\n@@ ') + text.startswith('@@ ')
             for text in (CARRIED_MUTEX, WASI_STALE, WASI_COLLIDING, WASI_FOREIGN_MEMBER,
                          WASI_KNOWN_MEMBER, WASI_DECLARES_MEMBER, WASI_USES_DECLARED_MEMBER,
                          CARRIED_TRIVIAL, WASI_TRIVIAL_CONTEXT, WASI_SECOND_ON_SAME_FILE,
                          PROSE_PREAMBLE, INDEXED))),
        ('a patch with no hunk header parses to none',
         len(parse_patch('just prose, no diff at all\n')) == 0),
        ('a trailer outside a hunk body is read',
         parse_trailers(WASI_COLLIDING_DECLARED)
         == ['0033-Interface_Static-thread-safety-mutex-1157.patch']),
        ('a patch with no trailer yields none', parse_trailers(WASI_COLLIDING) == []),
        ('an `index` line is read against the right target',
         parse_index(INDEXED) == {'src/FoundationClasses/TKernel/OSD/OSD_Path.cxx':
                                  ('a39c0c84', '792070c6')}),
        ('a hand-trimmed patch has no index stamp, which is not a defect',
         parse_index(WASI_STALE) == {}),
        ('class_stem pools .cxx with .hxx',
         class_stem('a/OSD_File.cxx') == class_stem('b/OSD_File.hxx') == 'OSD_File'),
        ('substantive() rejects a lone brace and accepts a statement',
         not substantive('  {  ') and substantive('  return aTable;  ')),
        ('DECL_RE separates a declaration from an assignment',
         DECL_RE.match('  std::atomic_flag mySpinlock;') is not None
         and DECL_RE.match('  myFileChannel = open(aTmpName, O_CREAT, 0600);') is None),
    ]
    for name, ok in parser_cases:
        failed += not ok
        print('  %s %s' % ('ok  ' if ok else 'MISS', name))

    total = len(cases) + len(parser_cases)
    print('%d/%d cases correct' % (total - failed, total))
    return 1 if failed else 0


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument('--self-test', action='store_true',
                        help='run the fixture battery instead of the repo')
    parser.add_argument('--list', action='store_true',
                        help='print each WASI patch\'s targets, trailers and index stamps')
    parser.add_argument('--tree', nargs='?', const=DEFAULT_TREE, default=None, metavar='DIR',
                        help='also run the real `git apply --check` in this checkout with the '
                             'carried set applied (default %s); not part of gate-scripts, which '
                             'has no checkout' % DEFAULT_TREE)
    parser.add_argument('--require-tree', action='store_true',
                        help='fail rather than skip when --tree examined nothing (#2098)')
    args = parser.parse_args()
    if args.self_test:
        return self_test()
    if args.list:
        return list_inventory()
    if args.require_tree and args.tree is None:
        args.tree = DEFAULT_TREE
    return run(tree=args.tree, require_tree=args.require_tree)


if __name__ == '__main__':
    os.chdir(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))
    sys.exit(main())
