#!/usr/bin/env bash
#
# clang-format the OCCTBridge C++ layer, or check that it is already formatted.
#
# One implementation, three callers: CI's `code-style` job, the optional pre-commit hook, and you.
# The previous arrangement had CI carry the file-selection and check loop inline while the hook
# carried nothing at all, so a contributor's only way to find a violation was to push and wait.
# Routing all three through this script means CI and local cannot run different things, which is
# the same property the pre-commit hook's header claims for the Python gates.
#
#   Scripts/format-bridge.sh                  # fix: rewrite every enforced bridge file in place
#   Scripts/format-bridge.sh --check          # report only, exit 1 on a violation (CI, the hook)
#   Scripts/format-bridge.sh path/to/One.mm   # fix just these files, manifest or not
#   Scripts/format-bridge.sh --check One.mm   # check just these files
#   Scripts/format-bridge.sh --self-test      # prove the checker still catches a violation
#   Scripts/format-bridge.sh --print-version  # resolved clang-format version, for CI's assertion
#
# SCOPE: the bridge only. There is deliberately no Swift half. `swift-format lint --strict` reports
# findings that are not mechanically fixable (BeginDocumentationCommentWithOneLineSummary wants a
# sentence rewritten, not a line rewrapped), so a script called "format" that silently left those
# behind would be worse than no script. clang-format has no such class: everything it reports, it
# fixes. Run `swift-format format -i --configuration .swift-format <file>` by hand for the Swift
# side, then re-lint, and expect to edit prose afterwards.
#
# VERSION: pinned in Scripts/clang-format-version.txt, see that file for why. A clang-format whose
# MAJOR differs from the pin is refused outright (exit 2), because major versions genuinely
# disagree about this config's output; a differing minor/patch only warns.

set -uo pipefail

INVOCATION_DIR="$PWD"
cd "$(git rev-parse --show-toplevel)" || {
    echo "format-bridge: not inside a git work tree." >&2
    exit 2
}

VERSION_FILE="Scripts/clang-format-version.txt"
MANIFEST="Scripts/style-manifest-bridge.txt"
CONFIG="Sources/OCCTBridge/.clang-format"

CF="${CLANG_FORMAT:-clang-format}"

# --- helpers ----------------------------------------------------------------------------------

pinned_version() {
    grep -v '^#' "$VERSION_FILE" | grep -v '^[[:space:]]*$' | head -1 | tr -d '[:space:]'
}

# `clang-format --version` is "clang-format version 22.1.8" from the LLVM build and
# "clang-format version 22.1.8 (https://... hash)" from some distributions, so take the first
# dotted-number token rather than a fixed field.
actual_version() {
    "$CF" --version 2>/dev/null | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1
}

require_clang_format() {
    if ! command -v "$CF" >/dev/null 2>&1; then
        return 1
    fi
    return 0
}

# Refuse a major-version mismatch, warn on anything else that is not an exact match. Returns 2 to
# mean "refused" so callers can distinguish it from a formatting violation.
check_version() {
    local pinned actual
    # The self-test drives this script through `$0 --check` against throwaway files, and what it
    # proves (that the detector is not blind) holds at any clang-format version: the file it
    # expects to be accepted is generated by the same binary doing the checking. Coupling it to the
    # pin would make a contributor on the wrong major fail their pre-commit hook on a detector
    # question, when the only thing their version actually affects is the tree's own formatting,
    # which `--check` refuses outright a few lines below.
    if [ -n "${FORMAT_BRIDGE_SELFTEST:-}" ]; then
        return 0
    fi
    pinned="$(pinned_version)"
    actual="$(actual_version)"

    if [ -z "$actual" ]; then
        echo "format-bridge: could not parse a version out of \`$CF --version\`." >&2
        return 2
    fi
    if [ "$actual" = "$pinned" ]; then
        return 0
    fi
    if [ "${actual%%.*}" != "${pinned%%.*}" ]; then
        cat >&2 <<EOF
format-bridge: clang-format $actual, but this tree is formatted with $pinned.

Major versions disagree about this config's output, so formatting with $actual would produce a
diff CI rejects. Install the pinned build, e.g.

    python3 -m venv ~/.venvs/clang-format
    ~/.venvs/clang-format/bin/pip install "clang-format==$pinned"
    export PATH="\$HOME/.venvs/clang-format/bin:\$PATH"

or point this script at one: CLANG_FORMAT=/path/to/clang-format Scripts/format-bridge.sh
EOF
        return 2
    fi
    echo "format-bridge: warning: clang-format $actual, pinned $pinned (same major, output should" \
         "agree; CI is the authority)." >&2
    return 0
}

# The user's original question, answered mechanically rather than assumed: does `-style=file`
# actually resolve to Sources/OCCTBridge/.clang-format for this file? clang-format does not fail
# when it finds no config, it silently falls back to LLVM style, so "the check passed" and "the
# check ran against the wrong rules" look identical from the exit code alone. ColumnLimit is the
# fingerprint: 100 here, 80 in the LLVM fallback.
verify_config_discovery() {
    local probe="$1" resolved
    resolved="$("$CF" -style=file --dump-config "$probe" 2>/dev/null \
        | grep -E '^ColumnLimit:' | grep -oE '[0-9]+')"
    if [ "$resolved" != "100" ]; then
        cat >&2 <<EOF
format-bridge: -style=file did not resolve to $CONFIG for
  $probe
(ColumnLimit resolved to "${resolved:-<none>}", expected 100). clang-format falls back to LLVM
style rather than failing when it finds no .clang-format, so this would have checked the wrong
rules and reported nothing.
EOF
        return 2
    fi
    return 0
}

# CI used to inline this `comm`. It lives here now so the enforced set cannot differ between CI,
# the hook and a local run. A file leaves the manifest when it is brought into compliance, so the
# enforced set only ever grows.
enforced_files() {
    comm -23 \
        <(find Sources/OCCTBridge \( -name '*.h' -o -name '*.mm' \) | sort) \
        <(grep -v '^#' "$MANIFEST" | sort)
}

# --- self-test --------------------------------------------------------------------------------
#
# Guards the detector, not the tree: a --check that reports "all clear" because it is blind looks
# exactly like one reporting "all clear" because the bridge is clean. Case 4 is the one that would
# have answered the question this script was written for.

self_test() {
    require_clang_format || {
        echo "format-bridge --self-test: $CF not found." >&2
        exit 2
    }

    local tmp pass=0 fail=0
    tmp="$(mktemp -d)"

    export FORMAT_BRIDGE_SELFTEST=1

    ok()   { echo "  PASS  $1"; pass=$((pass + 1)); }
    bad()  { echo "  FAIL  $1"; fail=$((fail + 1)); }

    # A violation this config's own options produce: AlignConsecutiveAssignments wants the two
    # `=` aligned and AlignConsecutiveDeclarations wants the two names aligned.
    mkdir -p "$tmp/scoped"
    cp "$CONFIG" "$tmp/scoped/.clang-format"
    cat > "$tmp/scoped/bad.mm" <<'EOF'
void f()
{
  TopoDS_Edge e = g();
  int edgeIdx = h(e);
}
EOF
    "$CF" -style=file "$tmp/scoped/bad.mm" > "$tmp/scoped/good.mm"

    # 1. an unformatted file is reported
    if "$0" --check "$tmp/scoped/bad.mm" >/dev/null 2>&1; then
        bad "1. unformatted file reported"
    else
        ok "1. unformatted file reported"
    fi

    # 2. ...and a formatted one is not, so case 1 is not just "fails on everything"
    if "$0" --check "$tmp/scoped/good.mm" >/dev/null 2>&1; then
        ok "2. formatted file accepted"
    else
        bad "2. formatted file accepted"
    fi

    # 3. fix mode actually rewrites, and lands exactly on what --check accepts
    cp "$tmp/scoped/bad.mm" "$tmp/scoped/fixme.mm"
    "$0" "$tmp/scoped/fixme.mm" >/dev/null 2>&1
    if diff -q "$tmp/scoped/fixme.mm" "$tmp/scoped/good.mm" >/dev/null 2>&1; then
        ok "3. fix mode rewrites to the accepted form"
    else
        bad "3. fix mode rewrites to the accepted form"
    fi

    # 4. a file with no .clang-format above it is REFUSED, not silently checked against the LLVM
    #    fallback. Same bytes as case 2, which this config accepts and LLVM style does not, so a
    #    script that skipped the discovery check would report a violation here and blame the code.
    mkdir -p "$tmp/unscoped"
    cp "$tmp/scoped/good.mm" "$tmp/unscoped/good.mm"
    "$0" --check "$tmp/unscoped/good.mm" >"$tmp/out" 2>&1
    if [ $? -eq 2 ] && grep -q "did not resolve" "$tmp/out"; then
        ok "4. missing .clang-format refused, not silently downgraded to LLVM style"
    else
        bad "4. missing .clang-format refused, not silently downgraded to LLVM style"
    fi

    # 5. the enforced set is non-empty and every entry exists. An empty `comm` result makes --check
    #    exit 0 having checked nothing, which is this script's own way of going blind.
    local n
    n="$(enforced_files | wc -l | tr -d ' ')"
    if [ "$n" -gt 0 ] && [ "$(enforced_files | while read -r f; do [ -f "$f" ] || echo miss; done | wc -l | tr -d ' ')" = "0" ]; then
        ok "5. enforced set non-empty ($n files) and every entry exists"
    else
        bad "5. enforced set non-empty and every entry exists"
    fi

    rm -rf "$tmp"
    echo "format-bridge --self-test: $pass passed, $fail failed"
    [ "$fail" -eq 0 ]
}

# --- main -------------------------------------------------------------------------------------

MODE="fix"
FILES=()

while [ $# -gt 0 ]; do
    case "$1" in
        --check)         MODE="check" ;;
        --self-test)     MODE="self-test" ;;
        --print-version) MODE="print-version" ;;
        -h|--help)       sed -n '2,30p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
        -*)              echo "format-bridge: unknown option $1" >&2; exit 2 ;;
        *)
            # Resolve against the directory the user invoked from, since we have already cd'd to
            # the repo root.
            case "$1" in
                /*) FILES+=("$1") ;;
                *)  FILES+=("$INVOCATION_DIR/$1") ;;
            esac
            ;;
    esac
    shift
done

if [ "$MODE" = "self-test" ]; then
    self_test
    exit $?
fi

require_clang_format || {
    if [ "$MODE" = "check" ]; then
        echo "format-bridge: $CF not found; skipping the bridge format check (CI still runs it)." >&2
        exit 0
    fi
    echo "format-bridge: $CF not found. See $VERSION_FILE for the pinned version." >&2
    exit 2
}

if [ "$MODE" = "print-version" ]; then
    echo "pinned:   $(pinned_version)"
    echo "resolved: $(actual_version)  ($(command -v "$CF"))"
    check_version || exit 2
    exit 0
fi

check_version || exit 2

if [ ${#FILES[@]} -eq 0 ]; then
    while IFS= read -r f; do
        [ -n "$f" ] && FILES+=("$f")
    done < <(enforced_files)
fi

if [ ${#FILES[@]} -eq 0 ]; then
    echo "format-bridge: nothing to do, every bridge file is on $MANIFEST." >&2
    exit 0
fi

for d in $(printf '%s\n' "${FILES[@]}" | xargs -n1 dirname | sort -u); do
    probe="$(printf '%s\n' "${FILES[@]}" | grep "^$d/" | head -1)"
    verify_config_discovery "$probe" || exit 2
done

violations=0
for f in "${FILES[@]}"; do
    if [ ! -f "$f" ]; then
        echo "format-bridge: no such file: $f" >&2
        exit 2
    fi
    if [ "$MODE" = "check" ]; then
        "$CF" --dry-run --Werror -style=file "$f" || violations=1
    else
        "$CF" -i -style=file "$f"
    fi
done

# Printed on success too. A silent exit 0 cannot be told apart from a run that selected no files,
# and this line is what makes an unexpectedly small number visible in a CI log.
if [ "$MODE" = "check" ]; then
    echo "format-bridge: checked ${#FILES[@]} file(s) against $CONFIG with clang-format $(actual_version)."
    [ "$violations" -eq 0 ] || {
        echo "format-bridge: run \`Scripts/format-bridge.sh\` to fix the violations above." >&2
        exit 1
    }
else
    echo "format-bridge: formatted ${#FILES[@]} file(s) with clang-format $(actual_version)."
fi
exit 0
